/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package returningitandcs;

import javax.swing.ComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JPanel;
import returningitandcs.Command.Command;
import returningitandcs.Command.CreateStudentCommand;
import returningitandcs.Command.RemoteControl;

/**
 *
 * @author sandman
 */
public class AdvisingPortal extends javax.swing.JFrame {
    
    AdvisingSystem advisingSystem;
    RemoteControl systemControl;

    /**
     * Creates new form GUI
     */
    public AdvisingPortal() {
        initComponents();
    }
    
    public AdvisingPortal(AdvisingSystem advisingSystem, RemoteControl systemControl) {
        this.advisingSystem = advisingSystem;
        this.systemControl = systemControl;
        initComponents();
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        degreeBtnGroup = new javax.swing.ButtonGroup();
        yearBtnGroup = new javax.swing.ButtonGroup();
        semBtnGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        portalTitle = new javax.swing.JLabel();
        innerPanel = new javax.swing.JLayeredPane();
        FirstPanel = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        CSButton = new javax.swing.JRadioButton();
        ITButton = new javax.swing.JRadioButton();
        majorLabel = new javax.swing.JLabel();
        EnrollmentYearLabel = new javax.swing.JLabel();
        Y2Button = new javax.swing.JRadioButton();
        Y3Button = new javax.swing.JRadioButton();
        EnrollmentSemLabel = new javax.swing.JLabel();
        Sem1Button = new javax.swing.JRadioButton();
        Sem2Button = new javax.swing.JRadioButton();
        nextBtn = new javax.swing.JButton();
        gpaLabel = new javax.swing.JLabel();
        GPATextField = new javax.swing.JTextField();
        Year1Panel = new javax.swing.JPanel();
        Y1Title = new javax.swing.JLabel();
        Sem1Title = new javax.swing.JLabel();
        y1help = new javax.swing.JLabel();
        y1s1c1 = new javax.swing.JComboBox<>();
        y1s1c2 = new javax.swing.JComboBox<>();
        y1s1c3 = new javax.swing.JComboBox<>();
        y1s1c4 = new javax.swing.JComboBox<>();
        y1s1c5 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        y1s1g1 = new javax.swing.JTextField();
        y1s1g2 = new javax.swing.JTextField();
        y1s1g3 = new javax.swing.JTextField();
        y1s1g4 = new javax.swing.JTextField();
        y1s1g5 = new javax.swing.JTextField();
        y1s2g5 = new javax.swing.JTextField();
        y1s2g4 = new javax.swing.JTextField();
        y1s2g3 = new javax.swing.JTextField();
        y1s2g2 = new javax.swing.JTextField();
        y1s2g1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        y1s2c1 = new javax.swing.JComboBox<>();
        y1s2c2 = new javax.swing.JComboBox<>();
        y1s2c3 = new javax.swing.JComboBox<>();
        y1s2c4 = new javax.swing.JComboBox<>();
        y1s2c5 = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        y1s3c1 = new javax.swing.JComboBox<>();
        y1s3g1 = new javax.swing.JTextField();
        y1s3c2 = new javax.swing.JComboBox<>();
        y1s3g2 = new javax.swing.JTextField();
        y1s3c3 = new javax.swing.JComboBox<>();
        y1s3g3 = new javax.swing.JTextField();
        y1s3c4 = new javax.swing.JComboBox<>();
        y1s3g4 = new javax.swing.JTextField();
        y1s3c5 = new javax.swing.JComboBox<>();
        y1s3g5 = new javax.swing.JTextField();
        Y1Btn = new javax.swing.JButton();
        Year2Panel = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        y2s1c1 = new javax.swing.JComboBox<>();
        y2s1c4 = new javax.swing.JComboBox<>();
        y2s1c2 = new javax.swing.JComboBox<>();
        y2s1c3 = new javax.swing.JComboBox<>();
        y2s1c5 = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        y2s1g1 = new javax.swing.JTextField();
        y2s1g2 = new javax.swing.JTextField();
        y2s1g3 = new javax.swing.JTextField();
        y2s1g4 = new javax.swing.JTextField();
        y2s1g5 = new javax.swing.JTextField();
        y2s2g5 = new javax.swing.JTextField();
        y2s2g4 = new javax.swing.JTextField();
        y2s2g3 = new javax.swing.JTextField();
        y2s2g2 = new javax.swing.JTextField();
        y2s2g1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        y2s2c1 = new javax.swing.JComboBox<>();
        y2s2c2 = new javax.swing.JComboBox<>();
        y2s2c3 = new javax.swing.JComboBox<>();
        y2s2c4 = new javax.swing.JComboBox<>();
        y2s2c5 = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        y2s3c1 = new javax.swing.JComboBox<>();
        y2s3g1 = new javax.swing.JTextField();
        y2s3c2 = new javax.swing.JComboBox<>();
        y2s3g2 = new javax.swing.JTextField();
        y2s3c3 = new javax.swing.JComboBox<>();
        y2s3g3 = new javax.swing.JTextField();
        y2s3c4 = new javax.swing.JComboBox<>();
        y2s3g4 = new javax.swing.JTextField();
        y2s3c5 = new javax.swing.JComboBox<>();
        y2s3g5 = new javax.swing.JTextField();
        Y2Btn = new javax.swing.JButton();
        Year3Panel = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        y3s1c1 = new javax.swing.JComboBox<>();
        y3s1c4 = new javax.swing.JComboBox<>();
        y3s1c2 = new javax.swing.JComboBox<>();
        y3s1c3 = new javax.swing.JComboBox<>();
        y3s1c5 = new javax.swing.JComboBox<>();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        y3s1g1 = new javax.swing.JTextField();
        y3s1g2 = new javax.swing.JTextField();
        y3s1g3 = new javax.swing.JTextField();
        y3s1g4 = new javax.swing.JTextField();
        y3s1g5 = new javax.swing.JTextField();
        y3s2g5 = new javax.swing.JTextField();
        y3s2g4 = new javax.swing.JTextField();
        y3s2g3 = new javax.swing.JTextField();
        y3s2g2 = new javax.swing.JTextField();
        y3s2g1 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        y3s2c1 = new javax.swing.JComboBox<>();
        y3s2c2 = new javax.swing.JComboBox<>();
        y3s2c3 = new javax.swing.JComboBox<>();
        y3s2c4 = new javax.swing.JComboBox<>();
        y3s2c5 = new javax.swing.JComboBox<>();
        jLabel45 = new javax.swing.JLabel();
        genCourseBtn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        courseList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        portalTitle.setText("Advising");

        innerPanel.setLayout(new java.awt.CardLayout());

        FirstPanel.setBackground(new java.awt.Color(204, 255, 255));

        welcomeLabel.setText("Welcome");

        degreeBtnGroup.add(CSButton);
        CSButton.setText("Computer Science");
        CSButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CSButtonActionPerformed(evt);
            }
        });

        degreeBtnGroup.add(ITButton);
        ITButton.setText("Information Technology");

        majorLabel.setText("Select Your Major");

        EnrollmentYearLabel.setText("Select Enrollment Year");

        Y2Button.setText("2");
        Y2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Y2ButtonActionPerformed(evt);
            }
        });

        Y3Button.setText("3");

        EnrollmentSemLabel.setText("Select Enrollment Semester");

        Sem1Button.setText("1");

        Sem2Button.setText("2");

        nextBtn.setText("Next Page");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        gpaLabel.setText("Enter Your Current GPA");

        GPATextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GPATextFieldActionPerformed(evt);
            }
        });
        GPATextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                GPATextFieldKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout FirstPanelLayout = new javax.swing.GroupLayout(FirstPanel);
        FirstPanel.setLayout(FirstPanelLayout);
        FirstPanelLayout.setHorizontalGroup(
            FirstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FirstPanelLayout.createSequentialGroup()
                .addGap(439, 439, 439)
                .addComponent(nextBtn)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(FirstPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(FirstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(FirstPanelLayout.createSequentialGroup()
                        .addComponent(majorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(51, 51, 51)
                        .addComponent(CSButton))
                    .addComponent(welcomeLabel)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FirstPanelLayout.createSequentialGroup()
                        .addGroup(FirstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EnrollmentYearLabel)
                            .addComponent(EnrollmentSemLabel)
                            .addComponent(gpaLabel))
                        .addGap(51, 51, 51)
                        .addGroup(FirstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GPATextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Y2Button)
                            .addComponent(Sem1Button))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 309, Short.MAX_VALUE)
                .addGroup(FirstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FirstPanelLayout.createSequentialGroup()
                        .addComponent(ITButton)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FirstPanelLayout.createSequentialGroup()
                        .addComponent(Y3Button)
                        .addGap(209, 209, 209))
                    .addGroup(FirstPanelLayout.createSequentialGroup()
                        .addComponent(Sem2Button)
                        .addContainerGap())))
        );
        FirstPanelLayout.setVerticalGroup(
            FirstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FirstPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(welcomeLabel)
                .addGap(18, 18, 18)
                .addGroup(FirstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(majorLabel)
                    .addComponent(CSButton)
                    .addComponent(ITButton))
                .addGap(23, 23, 23)
                .addGroup(FirstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnrollmentYearLabel)
                    .addComponent(Y2Button)
                    .addComponent(Y3Button))
                .addGap(24, 24, 24)
                .addGroup(FirstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnrollmentSemLabel)
                    .addComponent(Sem1Button)
                    .addComponent(Sem2Button))
                .addGap(33, 33, 33)
                .addGroup(FirstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gpaLabel)
                    .addComponent(GPATextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(nextBtn)
                .addContainerGap(478, Short.MAX_VALUE))
        );

        innerPanel.add(FirstPanel, "card2");

        Year1Panel.setBackground(new java.awt.Color(204, 255, 204));

        Y1Title.setText("YEAR 1");

        Sem1Title.setText("Semester I");

        y1help.setText("Please select the courses you passed & the consecutive mark you received.");

        y1s1c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y1s1c1ActionPerformed(evt);
            }
        });

        jLabel19.setText("Grade");

        jLabel20.setText("Course");

        y1s1g1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y1s1g1ActionPerformed(evt);
            }
        });

        jLabel21.setText("Grade");

        jLabel22.setText("Course");

        jLabel23.setText("Semester II");

        jLabel24.setText("Summer");

        jLabel25.setText("Course");

        jLabel26.setText("Grade");

        y1s3g2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y1s3g2ActionPerformed(evt);
            }
        });

        y1s3g5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y1s3g5ActionPerformed(evt);
            }
        });

        Y1Btn.setText("Year 2 Options");
        Y1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Y1BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Year1PanelLayout = new javax.swing.GroupLayout(Year1Panel);
        Year1Panel.setLayout(Year1PanelLayout);
        Year1PanelLayout.setHorizontalGroup(
            Year1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Year1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Year1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(y1help)
                    .addGroup(Year1PanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Sem1Title)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Year1PanelLayout.createSequentialGroup()
                .addGroup(Year1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Year1PanelLayout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(Y1Title))
                    .addGroup(Year1PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Year1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Year1PanelLayout.createSequentialGroup()
                                .addGroup(Year1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Year1PanelLayout.createSequentialGroup()
                                        .addGroup(Year1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(y1s1c1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(y1s1c3, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(y1s1c4, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(y1s1c2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(Year1PanelLayout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel20))
                                            .addComponent(y1s1c5, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(69, 69, 69)
                                        .addGroup(Year1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(y1s1g5)
                                            .addComponent(jLabel19)
                                            .addComponent(y1s1g2)
                                            .addComponent(y1s1g3)
                                            .addComponent(y1s1g4)
                                            .addComponent(y1s1g1, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Year1PanelLayout.createSequentialGroup()
                                        .addGroup(Year1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(y1s2c1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(y1s2c2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(y1s2c3, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(y1s2c4, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(Year1PanelLayout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel22))
                                            .addComponent(y1s2c5, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(69, 69, 69)
                                        .addGroup(Year1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(Year1PanelLayout.createSequentialGroup()
                                                .addComponent(jLabel21)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(y1s2g2)
                                            .addComponent(y1s2g3)
                                            .addComponent(y1s2g4)
                                            .addComponent(y1s2g1)
                                            .addComponent(y1s2g5))))
                                .addGap(125, 125, 125)
                                .addComponent(Y1Btn))
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addGroup(Year1PanelLayout.createSequentialGroup()
                                .addGroup(Year1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(y1s3c1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(y1s3c2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(y1s3c3, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(y1s3c4, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(Year1PanelLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel25))
                                    .addComponent(y1s3c5, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(69, 69, 69)
                                .addGroup(Year1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(Year1PanelLayout.createSequentialGroup()
                                        .addGroup(Year1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(y1s3g5)
                                            .addComponent(y1s3g1)
                                            .addComponent(y1s3g2)
                                            .addComponent(y1s3g3, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(y1s3g4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addGap(321, 321, 321))
        );
        Year1PanelLayout.setVerticalGroup(
            Year1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Year1PanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Y1Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(y1help)
                .addGap(10, 10, 10)
                .addComponent(Sem1Title)
                .addGroup(Year1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Year1PanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(y1s1c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(y1s1c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(y1s1c4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(y1s1c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Year1PanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(Year1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Year1PanelLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(y1s1g1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(y1s1g2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(y1s1g3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35))
                            .addComponent(y1s1g4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Year1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(y1s1c5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(y1s1g5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jLabel23)
                .addGap(5, 5, 5)
                .addGroup(Year1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Year1PanelLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(y1s2c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(y1s2c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(y1s2c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(y1s2c4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Year1PanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(Year1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Year1PanelLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(y1s2g1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(y1s2g2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(y1s2g3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35))
                            .addComponent(y1s2g4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Year1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(y1s2c5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(y1s2g5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Year1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Year1PanelLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(y1s3c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(y1s3c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(y1s3c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(y1s3c4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(Year1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(y1s3c5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Y1Btn)))
                    .addGroup(Year1PanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Year1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Year1PanelLayout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(y1s3g4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Year1PanelLayout.createSequentialGroup()
                                .addComponent(y1s3g1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(y1s3g2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(y1s3g3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(7, 7, 7)
                        .addComponent(y1s3g5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );

        innerPanel.add(Year1Panel, "card3");

        Year2Panel.setBackground(new java.awt.Color(255, 153, 153));

        jLabel27.setText("YEAR 2");

        jLabel28.setText("Semester I");

        jLabel29.setText("Please select the courses you passed & the consecutive mark you received");

        jLabel30.setText("Grade");

        jLabel31.setText("Course");

        y2s2g4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y2s2g4ActionPerformed(evt);
            }
        });

        y2s2g3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y2s2g3ActionPerformed(evt);
            }
        });

        jLabel32.setText("Grade");

        jLabel33.setText("Course");

        jLabel34.setText("Semester II");

        jLabel35.setText("Summer");

        jLabel36.setText("Course");

        jLabel37.setText("Grade");

        y2s3g4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y2s3g4ActionPerformed(evt);
            }
        });

        Y2Btn.setText("Year 3 Options");
        Y2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Y2BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Year2PanelLayout = new javax.swing.GroupLayout(Year2Panel);
        Year2Panel.setLayout(Year2PanelLayout);
        Year2PanelLayout.setHorizontalGroup(
            Year2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Year2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Year2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addGroup(Year2PanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(Year2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Year2PanelLayout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addGap(27, 27, 27)
                                .addGroup(Year2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Year2PanelLayout.createSequentialGroup()
                                        .addGroup(Year2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(y2s1c1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(y2s1c2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(y2s1c3, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(y2s1c4, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(Year2PanelLayout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel31))
                                            .addComponent(y2s1c5, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(69, 69, 69)
                                        .addGroup(Year2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(y2s1g2)
                                            .addComponent(jLabel30)
                                            .addComponent(y2s1g3)
                                            .addComponent(y2s1g4)
                                            .addComponent(y2s1g5)
                                            .addComponent(y2s1g1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Year2PanelLayout.createSequentialGroup()
                                        .addGroup(Year2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(y2s2c1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(y2s2c2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(y2s2c3, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(y2s2c4, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(Year2PanelLayout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel33))
                                            .addComponent(y2s2c5, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(69, 69, 69)
                                        .addGroup(Year2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(y2s2g1)
                                            .addComponent(y2s2g2)
                                            .addComponent(y2s2g3)
                                            .addComponent(y2s2g4)
                                            .addGroup(Year2PanelLayout.createSequentialGroup()
                                                .addComponent(jLabel32)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(y2s2g5)))
                                    .addGroup(Year2PanelLayout.createSequentialGroup()
                                        .addGroup(Year2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(y2s3c1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(y2s3c2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(y2s3c3, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(y2s3c4, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(Year2PanelLayout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel36))
                                            .addComponent(y2s3c5, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(69, 69, 69)
                                        .addGroup(Year2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(y2s3g3)
                                            .addComponent(y2s3g2, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(y2s3g1, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(y2s3g4)
                                            .addGroup(Year2PanelLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel37)
                                                .addGap(71, 71, 71))
                                            .addComponent(y2s3g5))))
                                .addGap(87, 87, 87)
                                .addComponent(Y2Btn))
                            .addComponent(jLabel28)
                            .addComponent(jLabel35))))
                .addGap(0, 225, Short.MAX_VALUE))
            .addGroup(Year2PanelLayout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(jLabel27)
                .addGap(209, 209, 209))
        );
        Year2PanelLayout.setVerticalGroup(
            Year2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Year2PanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel27)
                .addGap(84, 84, 84)
                .addComponent(jLabel29)
                .addGap(10, 10, 10)
                .addComponent(jLabel28)
                .addGroup(Year2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Year2PanelLayout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel34)
                        .addGap(198, 198, 198)
                        .addComponent(jLabel35)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Year2PanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Year2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Year2PanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(y2s1g1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(y2s1g2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(y2s1g3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(y2s1g4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Year2PanelLayout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(y2s1c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(y2s1c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(y2s1c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(y2s1c4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Year2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(y2s1c5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(y2s1g5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Year2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Year2PanelLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(Year2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Year2PanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel32)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(y2s2g1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(y2s2g2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(y2s2g3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41))
                                    .addGroup(Year2PanelLayout.createSequentialGroup()
                                        .addComponent(jLabel33)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(y2s2c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(y2s2c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(y2s2c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(y2s2c4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Year2PanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(y2s2g4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(Year2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(y2s2c5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(y2s2g5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(Year2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Year2PanelLayout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(y2s3c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(y2s3c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(y2s3c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(y2s3c4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(y2s3c5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Year2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Y2Btn)
                                .addGroup(Year2PanelLayout.createSequentialGroup()
                                    .addComponent(jLabel37)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(y2s3g1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(y2s3g2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(Year2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(Year2PanelLayout.createSequentialGroup()
                                            .addComponent(y2s3g3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(35, 35, 35))
                                        .addComponent(y2s3g4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(6, 6, 6)
                                    .addComponent(y2s3g5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
        );

        innerPanel.add(Year2Panel, "card4");

        Year3Panel.setBackground(new java.awt.Color(204, 204, 255));

        jLabel38.setText("YEAR 3");

        jLabel39.setText("Semester I");

        jLabel40.setText("Please select the courses you passed & the consecutive mark you received");

        jLabel41.setText("Grade");

        jLabel42.setText("Course");

        y3s1g2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y3s1g2ActionPerformed(evt);
            }
        });

        y3s1g3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y3s1g3ActionPerformed(evt);
            }
        });

        y3s2g2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y3s2g2ActionPerformed(evt);
            }
        });

        jLabel43.setText("Grade");

        jLabel44.setText("Course");

        jLabel45.setText("Semester II");

        genCourseBtn.setText("Generate Courses");
        genCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genCourseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Year3PanelLayout = new javax.swing.GroupLayout(Year3Panel);
        Year3Panel.setLayout(Year3PanelLayout);
        Year3PanelLayout.setHorizontalGroup(
            Year3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Year3PanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(Year3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40)
                    .addGroup(Year3PanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(Year3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Year3PanelLayout.createSequentialGroup()
                                .addComponent(jLabel45)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Year3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(y3s1c1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(y3s1c2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(y3s1c3, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(y3s1c4, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(Year3PanelLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel42))
                                    .addComponent(y3s1c5, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(y3s2c1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(y3s2c2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(y3s2c3, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(y3s2c4, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(Year3PanelLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel44))
                                    .addComponent(y3s2c5, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(145, 145, 145)
                                .addGroup(Year3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(y3s1g5)
                                    .addComponent(jLabel41)
                                    .addComponent(y3s1g4)
                                    .addComponent(y3s1g3)
                                    .addComponent(y3s1g2)
                                    .addComponent(y3s1g1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(y3s2g5)
                                    .addGroup(Year3PanelLayout.createSequentialGroup()
                                        .addComponent(jLabel43)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(y3s2g4)
                                    .addComponent(y3s2g3)
                                    .addComponent(y3s2g2)
                                    .addComponent(y3s2g1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel39))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Year3PanelLayout.createSequentialGroup()
                .addGroup(Year3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Year3PanelLayout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel38))
                    .addGroup(Year3PanelLayout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(genCourseBtn)))
                .addGap(209, 513, Short.MAX_VALUE))
        );
        Year3PanelLayout.setVerticalGroup(
            Year3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Year3PanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(Year3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Year3PanelLayout.createSequentialGroup()
                        .addComponent(jLabel41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(y3s1g1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(y3s1g2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(y3s1g3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(y3s1g4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(y3s1g5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel43)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(y3s2g1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(y3s2g2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(y3s2g3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(y3s2g4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(y3s2g5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Year3PanelLayout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addGap(84, 84, 84)
                        .addComponent(jLabel40)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel39)
                        .addGap(18, 18, 18)
                        .addGroup(Year3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Year3PanelLayout.createSequentialGroup()
                                .addGap(207, 207, 207)
                                .addComponent(jLabel45))
                            .addGroup(Year3PanelLayout.createSequentialGroup()
                                .addComponent(jLabel42)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(y3s1c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(y3s1c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(y3s1c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(y3s1c4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(y3s1c5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel44)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(y3s2c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(y3s2c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(y3s2c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(y3s2c4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(y3s2c5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(genCourseBtn)
                .addGap(81, 81, 81))
        );

        innerPanel.add(Year3Panel, "card5");

        jLabel5.setText("Enter the courses you are interested In");

        courseList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(courseList);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        innerPanel.add(jPanel6, "card6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(innerPanel)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(346, 346, 346)
                .addComponent(portalTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(portalTitle)
                .addGap(25, 25, 25)
                .addComponent(innerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CSButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CSButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CSButtonActionPerformed

    private void Y2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Y2ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Y2ButtonActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        // TODO add your handling code here:
        String degreeOpt = "";
        int yearOpt = 0, semOpt = 0;
        
        
        if (CSButton.isSelected()) {
            degreeOpt = CSButton.getActionCommand();
        }
        
        else if (ITButton.isSelected()){
            degreeOpt = ITButton.getActionCommand();
        }
        
        if (Y2Button.isSelected()) {
            yearOpt = Integer.parseInt(Y2Button.getActionCommand());
        }
        else if (Y3Button.isSelected()){
            yearOpt = Integer.parseInt(Y3Button.getActionCommand());
        }
        
        if (Sem1Button.isSelected()) {
            semOpt = Integer.parseInt(Sem1Button.getActionCommand());
        }
        else if (Sem2Button.isSelected()) {
            semOpt = Integer.parseInt(Sem2Button.getActionCommand());
        }
        
        String gpaText = GPATextField.getText();
        
            Double gpa = Double.parseDouble(gpaText);
            
            if (!degreeOpt.equals("") && yearOpt != 0 && semOpt != 0) {
                Command createStudent = new CreateStudentCommand(advisingSystem, degreeOpt,yearOpt,semOpt,gpa);
                systemControl.setCommand(createStudent);
                systemControl.pressButton();
                
                setComboBoxOptions();
                switchPanels(Year1Panel);
            }
            else {
                welcomeLabel.setText("Please fill out all fields.");
            }
            
    }//GEN-LAST:event_nextBtnActionPerformed

    private void Y1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Y1BtnActionPerformed
        // TODO add your handling code here:
        Course c;
        switchPanels(Year2Panel);
    }//GEN-LAST:event_Y1BtnActionPerformed

    private void y1s1g1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y1s1g1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y1s1g1ActionPerformed

    private void GPATextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GPATextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GPATextFieldActionPerformed

    private void y1s3g2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y1s3g2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y1s3g2ActionPerformed

    private void y1s3g5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y1s3g5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y1s3g5ActionPerformed

    private void y1s1c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y1s1c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y1s1c1ActionPerformed

    private void GPATextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GPATextFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_GPATextFieldKeyPressed

    private void y2s2g3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y2s2g3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y2s2g3ActionPerformed

    private void y2s2g4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y2s2g4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y2s2g4ActionPerformed

    private void y2s3g4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y2s3g4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y2s3g4ActionPerformed

    private void Y2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Y2BtnActionPerformed
        // TODO add your handling code here:
        switchPanels(Year3Panel);
    }//GEN-LAST:event_Y2BtnActionPerformed

    private void y3s1g2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y3s1g2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y3s1g2ActionPerformed

    private void y3s1g3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y3s1g3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y3s1g3ActionPerformed

    private void y3s2g2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y3s2g2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y3s2g2ActionPerformed

    private void genCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genCourseBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genCourseBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdvisingPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdvisingPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdvisingPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdvisingPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdvisingPortal().setVisible(true);
            }
        });
    }
    
    /***
     * 
     * Method to switch panels using layered panels with card layout
     */
    public void switchPanels(JPanel panel) {
        innerPanel.removeAll();
        innerPanel.add(panel);
        innerPanel.repaint();
        innerPanel.revalidate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CSButton;
    private javax.swing.JLabel EnrollmentSemLabel;
    private javax.swing.JLabel EnrollmentYearLabel;
    private javax.swing.JPanel FirstPanel;
    private javax.swing.JTextField GPATextField;
    private javax.swing.JRadioButton ITButton;
    private javax.swing.JRadioButton Sem1Button;
    private javax.swing.JLabel Sem1Title;
    private javax.swing.JRadioButton Sem2Button;
    private javax.swing.JButton Y1Btn;
    private javax.swing.JLabel Y1Title;
    private javax.swing.JButton Y2Btn;
    private javax.swing.JRadioButton Y2Button;
    private javax.swing.JRadioButton Y3Button;
    private javax.swing.JPanel Year1Panel;
    private javax.swing.JPanel Year2Panel;
    private javax.swing.JPanel Year3Panel;
    private javax.swing.JList<String> courseList;
    private javax.swing.ButtonGroup degreeBtnGroup;
    private javax.swing.JButton genCourseBtn;
    private javax.swing.JLabel gpaLabel;
    private javax.swing.JLayeredPane innerPanel;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel majorLabel;
    private javax.swing.JButton nextBtn;
    private javax.swing.JLabel portalTitle;
    private javax.swing.ButtonGroup semBtnGroup;
    private javax.swing.JLabel welcomeLabel;
    private javax.swing.JLabel y1help;
    private javax.swing.JComboBox<String> y1s1c1;
    private javax.swing.JComboBox<String> y1s1c2;
    private javax.swing.JComboBox<String> y1s1c3;
    private javax.swing.JComboBox<String> y1s1c4;
    private javax.swing.JComboBox<String> y1s1c5;
    private javax.swing.JTextField y1s1g1;
    private javax.swing.JTextField y1s1g2;
    private javax.swing.JTextField y1s1g3;
    private javax.swing.JTextField y1s1g4;
    private javax.swing.JTextField y1s1g5;
    private javax.swing.JComboBox<String> y1s2c1;
    private javax.swing.JComboBox<String> y1s2c2;
    private javax.swing.JComboBox<String> y1s2c3;
    private javax.swing.JComboBox<String> y1s2c4;
    private javax.swing.JComboBox<String> y1s2c5;
    private javax.swing.JTextField y1s2g1;
    private javax.swing.JTextField y1s2g2;
    private javax.swing.JTextField y1s2g3;
    private javax.swing.JTextField y1s2g4;
    private javax.swing.JTextField y1s2g5;
    private javax.swing.JComboBox<String> y1s3c1;
    private javax.swing.JComboBox<String> y1s3c2;
    private javax.swing.JComboBox<String> y1s3c3;
    private javax.swing.JComboBox<String> y1s3c4;
    private javax.swing.JComboBox<String> y1s3c5;
    private javax.swing.JTextField y1s3g1;
    private javax.swing.JTextField y1s3g2;
    private javax.swing.JTextField y1s3g3;
    private javax.swing.JTextField y1s3g4;
    private javax.swing.JTextField y1s3g5;
    private javax.swing.JComboBox<String> y2s1c1;
    private javax.swing.JComboBox<String> y2s1c2;
    private javax.swing.JComboBox<String> y2s1c3;
    private javax.swing.JComboBox<String> y2s1c4;
    private javax.swing.JComboBox<String> y2s1c5;
    private javax.swing.JTextField y2s1g1;
    private javax.swing.JTextField y2s1g2;
    private javax.swing.JTextField y2s1g3;
    private javax.swing.JTextField y2s1g4;
    private javax.swing.JTextField y2s1g5;
    private javax.swing.JComboBox<String> y2s2c1;
    private javax.swing.JComboBox<String> y2s2c2;
    private javax.swing.JComboBox<String> y2s2c3;
    private javax.swing.JComboBox<String> y2s2c4;
    private javax.swing.JComboBox<String> y2s2c5;
    private javax.swing.JTextField y2s2g1;
    private javax.swing.JTextField y2s2g2;
    private javax.swing.JTextField y2s2g3;
    private javax.swing.JTextField y2s2g4;
    private javax.swing.JTextField y2s2g5;
    private javax.swing.JComboBox<String> y2s3c1;
    private javax.swing.JComboBox<String> y2s3c2;
    private javax.swing.JComboBox<String> y2s3c3;
    private javax.swing.JComboBox<String> y2s3c4;
    private javax.swing.JComboBox<String> y2s3c5;
    private javax.swing.JTextField y2s3g1;
    private javax.swing.JTextField y2s3g2;
    private javax.swing.JTextField y2s3g3;
    private javax.swing.JTextField y2s3g4;
    private javax.swing.JTextField y2s3g5;
    private javax.swing.JComboBox<String> y3s1c1;
    private javax.swing.JComboBox<String> y3s1c2;
    private javax.swing.JComboBox<String> y3s1c3;
    private javax.swing.JComboBox<String> y3s1c4;
    private javax.swing.JComboBox<String> y3s1c5;
    private javax.swing.JTextField y3s1g1;
    private javax.swing.JTextField y3s1g2;
    private javax.swing.JTextField y3s1g3;
    private javax.swing.JTextField y3s1g4;
    private javax.swing.JTextField y3s1g5;
    private javax.swing.JComboBox<String> y3s2c1;
    private javax.swing.JComboBox<String> y3s2c2;
    private javax.swing.JComboBox<String> y3s2c3;
    private javax.swing.JComboBox<String> y3s2c4;
    private javax.swing.JComboBox<String> y3s2c5;
    private javax.swing.JTextField y3s2g1;
    private javax.swing.JTextField y3s2g2;
    private javax.swing.JTextField y3s2g3;
    private javax.swing.JTextField y3s2g4;
    private javax.swing.JTextField y3s2g5;
    private javax.swing.ButtonGroup yearBtnGroup;
    // End of variables declaration//GEN-END:variables

    
    private void setComboBoxOptions() {
        //YEAR 1 Panel
        String[] y1s1options = advisingSystem.filterCourseList(1, 1);
        y1s1c1.setModel(new javax.swing.DefaultComboBoxModel(y1s1options));
        y1s1c1.setSelectedItem(null);
        y1s1c2.setModel(new javax.swing.DefaultComboBoxModel(y1s1options));
        y1s1c2.setSelectedItem(null);
        y1s1c3.setModel(new javax.swing.DefaultComboBoxModel(y1s1options));
        y1s1c3.setSelectedItem(null);
        y1s1c4.setModel(new javax.swing.DefaultComboBoxModel(y1s1options));
        y1s1c4.setSelectedItem(null);
        y1s1c5.setModel(new javax.swing.DefaultComboBoxModel(y1s1options));
        y1s1c5.setSelectedItem(null);
        
        String[] y1s2options = advisingSystem.filterCourseList(1, 2);
        y1s2c1.setModel(new javax.swing.DefaultComboBoxModel(y1s2options));
        y1s2c1.setSelectedItem(null);
        y1s2c2.setModel(new javax.swing.DefaultComboBoxModel(y1s2options));
        y1s2c2.setSelectedItem(null);
        y1s2c3.setModel(new javax.swing.DefaultComboBoxModel(y1s2options));
        y1s2c3.setSelectedItem(null);
        y1s2c4.setModel(new javax.swing.DefaultComboBoxModel(y1s2options));
        y1s2c4.setSelectedItem(null);
        y1s2c5.setModel(new javax.swing.DefaultComboBoxModel(y1s2options));
        y1s2c5.setSelectedItem(null);
        
        //SUMMER
        String[] y1s3options = new String[y1s1options.length + y1s2options.length-1];
        System.arraycopy(y1s1options, 0, y1s3options, 0, y1s1options.length);
        System.arraycopy(y1s2options, 0, y1s3options, y1s1options.length, y1s2options.length-1);
        y1s3c1.setModel(new javax.swing.DefaultComboBoxModel(y1s3options));
        y1s3c1.setSelectedItem(null);
        y1s3c2.setModel(new javax.swing.DefaultComboBoxModel(y1s3options));
        y1s3c2.setSelectedItem(null);
        y1s3c3.setModel(new javax.swing.DefaultComboBoxModel(y1s3options));
        y1s3c3.setSelectedItem(null);
        y1s3c4.setModel(new javax.swing.DefaultComboBoxModel(y1s3options));
        y1s3c4.setSelectedItem(null);
        y1s3c5.setModel(new javax.swing.DefaultComboBoxModel(y1s3options));
        y1s3c5.setSelectedItem(null);
        
        
        //YEAR 2 Panel
        String[] y2s1options = advisingSystem.filterCourseList(2, 1);
        y2s1c1.setModel(new javax.swing.DefaultComboBoxModel(y2s1options));
        y2s1c1.setSelectedItem(null);
        y2s1c2.setModel(new javax.swing.DefaultComboBoxModel(y2s1options));
        y2s1c2.setSelectedItem(null);
        y2s1c3.setModel(new javax.swing.DefaultComboBoxModel(y2s1options));
        y2s1c3.setSelectedItem(null);
        y2s1c4.setModel(new javax.swing.DefaultComboBoxModel(y2s1options));
        y2s1c4.setSelectedItem(null);
        y2s1c5.setModel(new javax.swing.DefaultComboBoxModel(y2s1options));
        y2s1c5.setSelectedItem(null);
        
        
        String[] y2s2options = advisingSystem.filterCourseList(2, 2);
        y2s2c1.setModel(new javax.swing.DefaultComboBoxModel(y2s2options));
        y2s2c1.setSelectedItem(null);
        y2s2c2.setModel(new javax.swing.DefaultComboBoxModel(y2s2options));
        y2s2c2.setSelectedItem(null);
        y2s2c3.setModel(new javax.swing.DefaultComboBoxModel(y2s2options));
        y2s2c3.setSelectedItem(null);
        y2s2c4.setModel(new javax.swing.DefaultComboBoxModel(y2s2options));
        y2s2c4.setSelectedItem(null);
        y2s2c5.setModel(new javax.swing.DefaultComboBoxModel(y2s2options));
        y2s2c5.setSelectedItem(null);
        
        //SUMMER
        String[] y2s3options = new String[y2s1options.length + y2s2options.length-1];
        System.arraycopy(y2s1options, 0, y2s3options, 0, y2s1options.length);
        System.arraycopy(y2s2options, 0, y2s3options, y2s1options.length, y2s2options.length-1);
        y2s3c1.setModel(new javax.swing.DefaultComboBoxModel(y2s3options));
        y2s3c1.setSelectedItem(null);
        y2s3c2.setModel(new javax.swing.DefaultComboBoxModel(y2s3options));
        y2s3c2.setSelectedItem(null);
        y2s3c3.setModel(new javax.swing.DefaultComboBoxModel(y2s3options));
        y2s3c3.setSelectedItem(null);
        y2s3c4.setModel(new javax.swing.DefaultComboBoxModel(y2s3options));
        y2s3c4.setSelectedItem(null);
        y2s3c5.setModel(new javax.swing.DefaultComboBoxModel(y2s3options));
        y2s3c5.setSelectedItem(null);
        
        //YEAR 3
        String[] y3s1options = advisingSystem.filterCourseList(2, 1);
        y3s1c1.setModel(new javax.swing.DefaultComboBoxModel(y3s1options));
        y3s1c1.setSelectedItem(null);
        y3s1c2.setModel(new javax.swing.DefaultComboBoxModel(y3s1options));
        y3s1c2.setSelectedItem(null);
        y3s1c3.setModel(new javax.swing.DefaultComboBoxModel(y3s1options));
        y3s1c3.setSelectedItem(null);
        y3s1c4.setModel(new javax.swing.DefaultComboBoxModel(y3s1options));
        y3s1c4.setSelectedItem(null);
        y3s1c5.setModel(new javax.swing.DefaultComboBoxModel(y3s1options));
        y3s1c5.setSelectedItem(null);
        
        
        String[] y3s2options = advisingSystem.filterCourseList(2, 2);
        y3s2c1.setModel(new javax.swing.DefaultComboBoxModel(y3s2options));
        y3s2c1.setSelectedItem(null);
        y3s2c2.setModel(new javax.swing.DefaultComboBoxModel(y3s2options));
        y3s2c2.setSelectedItem(null);
        y3s2c3.setModel(new javax.swing.DefaultComboBoxModel(y3s2options));
        y3s2c3.setSelectedItem(null);
        y3s2c4.setModel(new javax.swing.DefaultComboBoxModel(y3s2options));
        y3s2c4.setSelectedItem(null);
        y3s2c5.setModel(new javax.swing.DefaultComboBoxModel(y3s2options));
        y3s2c5.setSelectedItem(null);
    }


}
